# !/usr/bin/python2
# -*- coding: utf-8 -*-

SETTINGS_PRIORITY = 10

import logging

APP_LOG_FILENAME = 'pythonvideoannotator.log'
APP_LOG_HANDLER_FILE_LEVEL = logging.DEBUG
APP_LOG_HANDLER_CONSOLE_LEVEL = logging.INFO

PYFORMS_LOG_HANDLER_FILE_LEVEL = logging.DEBUG
PYFORMS_LOG_HANDLER_CONSOLE_LEVEL = logging.INFO

SAVED_VIDEO_FILE_PATH = ""
SAVED_GRAPH_FILE_PATH = ""
SAVED_BONSAI_FILE_PATH = ""

GENERIC_EDITOR_WINDOW_GEOMETRY = 100, 100, 800, 600
